### ISSUE TITLE
Download fails for MS Edge / Win 10

### ISSUE THREAD

**Issue by amigolargo** [xdissent/ievms#288] opened 2015-12-14 12:54 UTC
https://az792536.vo.msecnd.net/vms/VMBuild_20150801/VirtualBox/MSEdge/Mac/Microsoft%20Edge.Win10.For.Mac.VirtualBox.zip

seems to be a dead link

**Comment by fabiosantoscode** [comment] 2015-12-14 13:58
Can reproduce from here.

**Comment by fabiosantoscode** [comment] 2015-12-14 15:11
I was going to create a [pull request](https://github.com/xdissent/ievms/compare/master...fabiosantoscode:patch-1) with the new URL and its MD5 but just updating it doesn't seem to be enough. `env IEVMS_VERSIONS="EDGE" bash ievms.sh` yields the following error when I update the URL:

```
Creating MSEdge - Win10 VM (disk: /home/fabio/.ievms/MSEdge - Win10-disk1.vmdk)
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance read failed
VBoxManage: error: Could not open the OVA file '/home/fabio/.ievms/MSEdge - Win10.ova' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 307 of file VBoxManageAppliance.cpp
```

(Though this is the first time I'm using ievms on this machine and on elementaryOS so I'm not sure. I have installed all the other browser versions successfully though).

**Comment by tordans** [comment] 2015-12-15 17:45
+1 for this issue.
I managed to download and manually install the VM via https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

But it would be great to have it inside of ievms again.

**Comment by mysterycommand** [comment] 2015-12-17 17:32
I think I have a similar issue, although the error I get is "Appliance import failed"?
```
$ curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="11 EDGE" bash
Checking for VirtualBox
Checking for Oracle VM VirtualBox Extension Pack
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Downloading unar from http://theunarchiver.googlecode.com/files/unar1.5.zip to unar1.5.zip (attempt 1 of 3)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4201k  100 4201k    0     0  2259k      0  0:00:01  0:00:01 --:--:-- 2259k
MD5 check succeeded for unar1.5.zip
Archive:  unar1.5.zip
  inflating: lsar
  inflating: unar
Building IE 11 VM
Checking for existing OVA at /Users/mhayes/.ievms/IE9 - Win7.ova
Downloading OVA ZIP from http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE9_Win7.zip to IE9_Win7.zip (attempt 1 of 3)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4770M  100 4770M    0     0  7821k      0  0:10:24  0:10:24 --:--:-- 8259k
MD5 check succeeded for IE9_Win7.zip
Extracting OVA from /Users/mhayes/.ievms/IE9_Win7.zip
IE9_Win7.zip: Zip
  IE9 - Win7.ova  (5079366144 B)... OK.
Successfully extracted to "./IE9 - Win7.ova".
Checking for existing IE11 - Win7 VM
Creating IE11 - Win7 VM (disk: /Users/mhayes/.ievms/IE11 - Win7-disk1.vmdk)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/mhayes/.ievms/IE9 - Win7.ova...
OK.
Disks:
  vmdisk1	135291469824	-1	http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized	IE9 - Win7-disk1.vmdk	-1	-1

Virtual system 0:
 0: Suggested OS type: "Windows7"
    (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
 1: VM name specified with --vmname: "IE11 - Win7"
 2: Number of CPUs: 2
    (change with "--vsys 0 --cpus <n>")
 3: Guest memory: 1024 MB
    (change with "--vsys 0 --memory <MB>")
 4: Sound card (appliance expects "", can change on import)
    (disable with "--vsys 0 --unit 4 --ignore")
 5: USB controller
    (disable with "--vsys 0 --unit 5 --ignore")
 6: Network adapter: orig NAT, config 3, extra slot=0;type=NAT
 7: CD-ROM
    (disable with "--vsys 0 --unit 7 --ignore")
 8: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 8 --ignore")
 9: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 9 --ignore")
10: SATA controller, type AHCI
    (disable with "--vsys 0 --unit 10 --ignore")
11: Hard disk image: source image=IE9 - Win7-disk1.vmdk, target path=/Users/mhayes/.ievms/IE11 - Win7-disk1.vmdk, controller=10;channel=0
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Machine settings file '/Users/mhayes/VirtualBox VMs/IE11 - Win7/IE11 - Win7.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp
```

**Comment by mysterycommand** [comment] 2015-12-17 18:01
Based on `Machine settings file '/Users/mhayes/VirtualBox VMs/IE11 - Win7/IE11 - Win7.vbox' already exists` I just removed `/Users/mhayes/VirtualBox VMs` and re-ran the script and it seems to have worked (for IE 11 … still having issues with IE Edge).

**Comment by cdata** [comment] 2015-12-17 22:36
Hey guys, I think that this is a dupe of #274 - there are workaround instructions here: https://github.com/xdissent/ievms/issues/274#issuecomment-159412949.

**Comment by tordans** [comment] 2015-12-18 06:37
Yes, it is @cdata. Can anyone close this one?

**Closed** 2015-12-18 08:35 UTC
